apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: expense
  labels:
    app: nginx
    tier: web
spec:
  containers: #docker run -d --name-nginx nginx
  - name: debug
    image: yashdwar/debug:v1


