apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend
  namespace: expense
  labels:
    app: frontend
    tier: web
    project: expense
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      tier: web
      project: expense
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
        tier: web
        project: expense
    spec:
      containers:
        - name: frontend
          image: yashdwar/frontend:v2
---
kind: Service
type: LoadBalancer
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec:
  selector:
      app: frontend
      tier: web
      project: expense
  ports:
  - name: frontend
    protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container port
