apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
  namespace: expense
  labels:
    tier: backend
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
      project: expense
  template:
    metadata:
      name: backend
      labels:
        tier: backend
        project: expense
    spec:
      initContainers:
      - name: init-mysql
        image: busybox:1.28
        command: ['sh', '-c', "until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done"]
      containers:
        - name: backend
          image: yashdwar/backend:v2
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15 #initial delay
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    tier: backend
    project: expense
  ports:
  - name: backend
    protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container port
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend
  namespace: expense
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment   #this targets only deployment not pod, since only there scalability is leveraged with no.of pods
    name: backend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 15 #usally 75 in realtime