apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    tier: api
    component: db
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: api
      project: db
  template:
    metadata:
      labels:
        tier: api
        component: db
    spec:
      containers:
      - name: mysql
        image: yashdwar/mysql:v1
      

